AllCops:
  NewCops: disable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Max: 400

Metrics/ParameterLists:
  Max: 25

Style/IfUnlessModifier:
  Enabled: false